### ISSUE TITLE
Socket connection refused error

### ISSUE THREAD

**Issue by paktor132** [openeventdata/stanford_pipeline#9]
Hello, I'm trying to run stanford_pipeline, and I'm getting the following error:
vagrant@eldiablo:~/stanford_pipeline$ cd /home/vagrant/stanford_pipeline && /usr/bin/python /home/vagrant/stanford_pipeline/process.py 
INFO:stanford:Running.
INFO:stanford:Returning 1178 total stories.
INFO:stanford:Setting up CoreNLP.
INFO:StanfordSocketWrap:Starting pipe subprocess, and waiting for signal it's ready, with command:  exec java -Xmx4g -cp /usr/local/lib/python2.7/dist-packages/stanford_corenlp_pywrapper/lib/piperunner.jar:/usr/local/lib/python2.7/dist-packages/stanford_corenlp_pywrapper/lib/guava-13.0.1.jar:/usr/local/lib/python2.7/dist-packages/stanford_corenlp_pywrapper/lib/jackson-all-1.9.11.jar:/home/vagrant/stanford-corenlp/stanford-corenlp-3.4.jar:/home/vagrant/stanford-corenlp/stanford-corenlp-3.4-models.jar:/home/vagrant/stanford-corenlp/stanford-srparser-2014-07-01-models.jar     corenlp.PipeCommandRunner --server 12340  --mode justparse --configfile stanford_config.ini
[Server] Using mode type: justparse
Adding annotator tokenize
Adding annotator ssplit

Adding annotator pos
Reading POS tagger model from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... INFO:StanfordSocketWrap:Waiting for startup: ping got exception: <class 'socket.error'> [Errno 111] Connection refused
INFO:StanfordSocketWrap:Waiting for startup: ping got exception: <class 'socket.error'> [Errno 111] Connection refused
done [4.5 sec].
Adding annotator parse
Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ...INFO:StanfordSocketWrap:Waiting for startup: ping got exception: <class 'socket.error'> [Errno 111] Connection refused
done [2.3 sec].
[Server] Using CoreNLP configuration file: stanford_config.ini
Adding annotator tokenize
Adding annotator ssplit
Adding annotator pos
Adding annotator lemma
Adding annotator parse
Loading parser from serialized file edu/stanford/nlp/models/srparser/englishSR.ser.gz ...INFO:StanfordSocketWrap:Waiting for startup: ping got exception: <class 'socket.error'> [Errno 111] Connection refused
INFO:StanfordSocketWrap:Waiting for startup: ping got exception: <class 'socket.error'> [Errno 111] Connection refused
INFO:StanfordSocketWrap:Waiting for startup: ping got exception: <class 'socket.error'> [Errno 111] Connection refused
INFO:StanfordSocketWrap:Waiting for startup: ping got exception: <class 'socket.error'> [Errno 111] Connection refused
INFO:StanfordSocketWrap:Waiting for startup: ping got exception: <class 'socket.error'> [Errno 111] Connection refused
INFO:StanfordSocketWrap:Waiting for startup: ping got exception: <class 'socket.error'> [Errno 111] Connection refused
INFO:StanfordSocketWrap:Waiting for startup: ping got exception: <class 'socket.error'> [Errno 111] Connection refused
INFO:StanfordSocketWrap:Waiting for startup: ping got exception: <class 'socket.error'> [Errno 111] Connection
 refused
INFO:StanfordSocketWrap:Waiting for startup: ping got exception: <class 'socket.error'> [Errno 111] Connection
 refused
INFO:StanfordSocketWrap:Waiting for startup: ping got exception: <class 'socket.error'> [Errno 111] Connection
 refused
INFO:StanfordSocketWrap:Waiting for startup: ping got exception: <class 'socket.error'> [Errno 111] Connection
 refused
INFO:StanfordSocketWrap:Waiting for startup: ping got exception: <class 'socket.error'> [Errno 111] Connection
 refused
^CTraceback (most recent call last):
  File "/home/vagrant/stanford_pipeline/process.py", line 145, in <module>
    main()
  File "/home/vagrant/stanford_pipeline/process.py", line 141, in main
    parser.stanford_parse(coll, stories, stanford_dir)
  File "/home/vagrant/stanford_pipeline/parser.py", line 33, in stanford_parse
    corenlp_libdir=stanford)
  File "/usr/local/lib/python2.7/dist-packages/stanford_corenlp_pywrapper/sockwrap.py", line 82, in __init__
    self.start_server()
  File "/usr/local/lib/python2.7/dist-packages/stanford_corenlp_pywrapper/sockwrap.py", line 99, in start_serv
er
    time.sleep(STARTUP_BUSY_WAIT_INTERVAL_SEC)
KeyboardInterrupt
WARNING:StanfordSocketWrap:Killing subprocess 28486
vagrant@eldiablo:~/stanford_pipeline$ 

Any thoughts on how to fix this?

Thanks,
Matt

**Comment by paktor132** [comment]
OK, I found a workaround at https://github.com/brendano/stanford_corenlp_pywrapper/issues/10. You need to increase the value of STARTUP_BUSY_WAIT_INTERVAL_SEC in /usr/local/lib/python2.7/dist-packages/stanford_corenlp_pywrapper/sockwrap.py (it's initially set at 2.0). When I set it to 200, as recommended on that other page, the code now runs fine.
